import { NextPage } from 'next';
// Hocks
import withApollo from 'hocs/withApollo';
// Layout
import LayoutWrapper from 'layouts/LayoutWrapper/LayoutWrapper';
// Components
import HomePage from 'components/HomePage/HomePage';

const Home: NextPage = () => {
  return (
    <LayoutWrapper
      title="Create Next App"
      description="Generated by create next app"
    >
      <HomePage />
    </LayoutWrapper>
  );
};

export default withApollo(Home);
