// Layouts
import LayoutWrapper from 'layouts/LayoutWrapper/LayoutWrapper';

const NewPage = () => {
  return (
    <LayoutWrapper title="Something" description="Generated by create next app">
      <div>This is some new page</div>
    </LayoutWrapper>
  );
};

export default NewPage;
